### ISSUE TITLE
Overview & Status

### ISSUE THREAD

**Issue by vaheminasyan2** [vaheminasyan2/Mammoths#17]
# Overview
**Project Title:** Mammoth 
**Team Member:** Bhavin, Vahe, Curtis, Joseph 
**Project Description:** A way to log workouts of varying types and share/compare with other users. 
 **General Idea:** Allow people to log workouts, track/compare data, generate workouts/training plans 
**Target audience:** General public 
**Problem:** Tracking progress of workouts, getting workout ideas, [collaboration] 
**Goal:** Create a workout log that interacts with database, has user profiles 

## APIs to be used:
- [x] Google Maps API for drawing custom route on map
- [ ] YouTube API / video source API  

## User stories:
- [x] US1: As a user, I want to create a Mammoth profile so that I can track my data. 
- [x] US2: As a Mammoth user, I want to log in so that I can access/view my data. 
- [x] US3: As a user, I want to enter my run/routes information. 
- [x] US4: As a user, I want to see my previous workout information so that I can assess my progress. 
- [ ] US5: As a user, I want to create a custom/use a template workout plan 
- [ ] US6: As a user, I want to browse for workout plan ideas 

## Pages of the application:
- [x] Log in  
- [x] Dashboard 
- [x] Post New Activity Page
- [ ] Run detail page

## Split and conquer:  
**Vahe:** login page, user authentication, routing, MySQL, Sequelize
**Bhavin:** MySQL, user authentication, Sequelize
**Joseph:** Design, dashboard/charts, CSS 
**Curtis:** Layout, run/routes templates, routing, Google API 

## Milestones:  
- [x] Jan. 31 (Thursday): Outline project 
- [x] Feb. 2 (Saturday): create models 
- [x] Feb. 5 (Tuesday): templates for each page 
- [x] Feb. 7 (Thursday): login/user authentication figured out 
- [x] Feb. 9 (Saturday): working app - Sprint 1 is complete
- [ ] Feb. 12 (Tuesday): polish running functionality and/or add additional feature
- [ ] Feb. 14 (Thursday): Prepare for presentation
- [ ] Feb. 16 (Saturday): Presentation 

## To-dos:
- [ ] Enable view run which will open a new page with run details after click on specific run - **Vahe**
- [ ] Load and display last 5 routes in the post activity page. Move the Load Route button into the map area if possible or somewhere else
- [ ] Display a bar graph of last five runs by date for logged in user 
- [ ] Add functionality to load friends runs by adding  friends email address. Display user's and his friends runs in one graph on the dashboard
- [ ] Add a test for one GET and POST route
- [ ] prepare for presentation

## To-do in polishing stage: 
- [x] Post Activity Form Validation: minutes <= 59, seconds <= 59
- [x] ** Post Activity, Mile Pace calculates as "NaNNaN" before user completes entry
- [x] Add "select one" to the Primary surface drop down
- [x] Bootstrap Load Route button
- [x] Replace "top runs/routes" with "recent runs/routes"
- [ ] Replace alerts in public/login.js and public/index.js with bootstrap modal or similar thing 
- [ ] **Save route** button saves empty route if nothing is selected
- [ ] **Undo last** button throws error if nothing to undo 
- [ ] Add end icon for last point in route

 ## Issues/ Learnings: 
- same id's in handlebar files like post-activity.js where distance id's for maps and run form were same
- If user Loops Route then clicks "Undo Last", user has to undo each leg that was looped. Ideally it would undo the entire Loop Route function
- API object didn't work for me in the post-activity.js. It'd throw API.xxx isn't function. I write that ajax call within my function where I called it.
- After joining second routes table with user I would see error Routes.UserID can't be null. I had to switch to less strick SQL mode which fixed this issue. I added this line of code to our schema file: `SET GLOBAL sql_mode='';`
- $ajax call didn't work in one of the files. It appeared that we were using slim version of jQuery which doesn't support ajax calling. I replaced it with this version:
 `<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>`

**Comment by vaheminasyan2** [comment]
> * Tuesday

u
